name: Build and Upload TinyJpgPngCompress (Self-contained, Zipped)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TinyJpgPngCompress/TinyJpgPngCompress.csproj

      - name: Build Release
        run: dotnet build TinyJpgPngCompress/TinyJpgPngCompress.csproj --configuration Release --no-restore

      - name: Publish (Self-contained win-x64)
        run: dotnet publish TinyJpgPngCompress/TinyJpgPngCompress.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

      - name: Zip Publish Output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./TinyJpgPngCompress-win-x64.zip

      - name: Upload Zipped Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TinyJpgPngCompress-win-x64
          path: ./TinyJpgPngCompress-win-x64.zip
